    php-voot-client:
        authorize_endpoint: "{BASE_URL}/php-oauth/authorize.php"
        client_id: php-voot-client
        client_secret: f00b4r
        token_endpoint: "{BASE_URL}/php-oauth/token.php"
